services:
  postgres:
    image: postgres:16-alpine
    container_name: oddycrm_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: oddycrm
      POSTGRES_PASSWORD: oddycrm_pass
      POSTGRES_DB: oddycrm
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  siarem_db:
    image: postgres:16-alpine
    container_name: siarem_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: oddycrm
      POSTGRES_PASSWORD: oddycrm_pass
      POSTGRES_DB: siarem_db
    ports:
      - "5440:5432"
    volumes:
      - siarem_db_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  siarem_db_data:
